/**
 * exportUtils.test.ts
 *
 * Tests for the Markdown export builder.
 *
 * buildMarkdown is the only part of the export path that can be tested without
 * a device: the native path needs expo-file-system and a share sheet, and the
 * web path needs a Clipboard API. Since the document it produces is what the
 * user actually walks away with, it is worth pinning down precisely.
 */

import { buildMarkdown } from '../exportUtils';
import { generateDoubleElimBracket } from '../bracketGenerator';
import { getAvailableMatches, recordResult } from '../doubleElimLogic';
import { Participant, Tournament } from '../../types/tournament';

// ─── Helpers ─────────────────────────────────────────────────────────────────

function participant(overrides: Partial<Participant> & { id: string; name: string }): Participant {
  return {
    wins: 0,
    losses: 0,
    eliminated: false,
    placement: null,
    ...overrides,
  };
}

function tournamentOf(participants: Participant[], overrides: Partial<Tournament> = {}): Tournament {
  return {
    id: 't1',
    name: 'Summer Championships',
    createdAt: '2026-06-14T10:30:00.000Z',
    status: 'complete',
    format: 'double-elimination',
    participants,
    matches: [],
    needsGrandFinalReset: false,
    ...overrides,
  };
}

/** Plays a real bracket to completion so the export can be exercised end to end. */
function playedTournament(n: number, seed: number): Tournament {
  let s = seed;
  const rng = () => {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    return s / 0x7fffffff;
  };

  const participants = Array.from({ length: n }, (_, i) =>
    participant({ id: `p${i + 1}`, name: `Player ${i + 1}` }),
  );
  let t = tournamentOf(participants, {
    status: 'active',
    matches: generateDoubleElimBracket(participants),
  });

  for (let guard = 0; guard < 500 && t.status !== 'complete'; guard++) {
    const available = getAvailableMatches(t);
    if (available.length === 0) break;
    const m = available[Math.floor(rng() * available.length)];
    const p1Wins = rng() < 0.5;
    t = recordResult(t, m.id, (p1Wins ? m.p1Id : m.p2Id)!, p1Wins ? 2 : 0, p1Wins ? 0 : 2);
  }
  return t;
}

// ─── Header ──────────────────────────────────────────────────────────────────

describe('buildMarkdown header', () => {
  it('leads with the tournament name and metadata', () => {
    const md = buildMarkdown(tournamentOf([]));
    const lines = md.split('\n');

    expect(lines[0]).toBe('# Summer Championships');
    expect(md).toContain('**Format:** Double Elimination');
    expect(md).toContain('**Status:** complete');
  });

  it('signs off so an exported file is identifiable', () => {
    expect(buildMarkdown(tournamentOf([]))).toContain('*Generated by BracketUp*');
  });
});

// ─── Standings ───────────────────────────────────────────────────────────────

describe('buildMarkdown standings', () => {
  const placed = [
    participant({ id: 'a', name: 'Ada', placement: 2, wins: 4, losses: 2 }),
    participant({ id: 'b', name: 'Grace', placement: 1, wins: 5, losses: 0 }),
    participant({ id: 'c', name: 'Alan', placement: 3, wins: 3, losses: 2 }),
    participant({ id: 'd', name: 'Edsger', placement: 4, wins: 1, losses: 2 }),
  ];

  it('orders players by placement regardless of input order', () => {
    const md = buildMarkdown(tournamentOf(placed));
    const rows = md.split('\n').filter((l) => l.startsWith('| ') && l.includes('W – '));

    expect(rows.map((r) => r.split('|')[2].trim())).toEqual(['Grace', 'Ada', 'Alan', 'Edsger']);
  });

  it('awards medals to the top three and plain numbers below', () => {
    const md = buildMarkdown(tournamentOf(placed));

    expect(md).toContain('🥇 1st');
    expect(md).toContain('🥈 2nd');
    expect(md).toContain('🥉 3rd');
    expect(md).toContain('4th');
  });

  it('renders win-loss records', () => {
    expect(buildMarkdown(tournamentOf(placed))).toContain('5W – 0L');
  });

  it('omits the standings table entirely when nobody is placed', () => {
    const unplaced = [participant({ id: 'a', name: 'Ada' })];
    expect(buildMarkdown(tournamentOf(unplaced))).not.toContain('## Final Standings');
  });
});

// ─── Match history ───────────────────────────────────────────────────────────

describe('buildMarkdown match history', () => {
  it('labels each bracket section, and distinguishes the grand final from its reset', () => {
    const t = playedTournament(8, 3);
    const md = buildMarkdown(t);

    expect(md).toContain('## Match History');
    expect(md).toContain('WB R1');
    expect(md).toContain('LB R1');
    expect(md).toContain('Grand Final');

    // The reset only appears when it was actually played.
    const resetPlayed = t.matches.some(
      (m) => m.bracket === 'grand-final' && m.round === 2 && m.status === 'complete',
    );
    expect(md.includes('GF Reset')).toBe(resetPlayed);
  });

  it('lists every played match exactly once and no byes', () => {
    const t = playedTournament(9, 5); // non-power-of-two, so byes exist
    const md = buildMarkdown(t);

    const played = t.matches.filter((m) => m.status === 'complete' && !m.isBye);
    const byes = t.matches.filter((m) => m.isBye);
    expect(byes.length).toBeGreaterThan(0); // guard: this fixture must actually have byes

    // Every table line in the section, minus the header row and its separator.
    const historyRows = md
      .split('## Match History')[1]
      .split('\n')
      .filter((l) => l.trim().startsWith('|'))
      .slice(2);

    expect(historyRows).toHaveLength(played.length);
  });

  it('marks the winner in bold', () => {
    const t = playedTournament(8, 7);
    const md = buildMarkdown(t);
    const champion = t.participants.find((p) => p.placement === 1)!;

    expect(md).toContain(`**${champion.name}**`);
  });

  it('skips matches whose participants cannot be resolved', () => {
    // A match referencing an unknown player id must not emit a broken row.
    const players = [
      participant({ id: 'a', name: 'Ada', placement: 1 }),
      participant({ id: 'b', name: 'Grace', placement: 2 }),
    ];
    const t = tournamentOf(players, {
      matches: [
        {
          id: 'm1',
          round: 1,
          bracket: 'winners',
          matchIndex: 0,
          p1Id: 'a',
          p2Id: 'ghost',
          p1Score: 2,
          p2Score: 0,
          winnerId: 'a',
          loserId: 'ghost',
          status: 'complete',
          isBye: false,
          winnerNextMatchId: null,
          winnerNextSlot: null,
          loserNextMatchId: null,
          loserNextSlot: null,
        },
      ],
    });

    expect(buildMarkdown(t)).not.toContain('ghost');
  });
});

// ─── Structural integrity ────────────────────────────────────────────────────

describe('buildMarkdown output is well-formed', () => {
  it('keeps table rows consistent with their headers', () => {
    const md = buildMarkdown(playedTournament(8, 11));

    for (const block of md.split('## ').slice(1)) {
      const rows = block.split('\n').filter((l) => l.trim().startsWith('|'));
      if (rows.length === 0) continue;

      // Row 0 is the header, row 1 the separator; every row needs equal columns.
      const columnCount = rows[0].split('|').length;
      expect(rows.every((r) => r.split('|').length === columnCount)).toBe(true);
      expect(rows[1]).toMatch(/^\|[-|]+\|$/);
    }
  });

  it('never emits a row containing an undefined or null', () => {
    const md = buildMarkdown(playedTournament(9, 13));
    expect(md).not.toMatch(/undefined|null|NaN/);
  });

  it('handles a tournament that is still in progress', () => {
    const participants = Array.from({ length: 8 }, (_, i) =>
      participant({ id: `p${i + 1}`, name: `Player ${i + 1}` }),
    );
    const inProgress = tournamentOf(participants, {
      status: 'active',
      matches: generateDoubleElimBracket(participants),
    });

    const md = buildMarkdown(inProgress);
    expect(md).toContain('**Status:** active');
    expect(md).not.toContain('## Final Standings'); // nobody placed yet
  });

  it('does not break on names containing Markdown characters', () => {
    const players = [
      participant({ id: 'a', name: 'Ada | Lovelace', placement: 1, wins: 2 }),
      participant({ id: 'b', name: '**Grace**', placement: 2, losses: 2 }),
    ];

    const md = buildMarkdown(tournamentOf(players));
    expect(md).toContain('Ada | Lovelace');
    expect(md).toContain('**Grace**');
  });
});
