/**
 * exportUtils.ts
 *
 * Exports tournament data as JSON or plain-text summary, then shares via
 * the device share sheet using expo-sharing.
 */

import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { Tournament } from '../types/tournament';

// ─── JSON export ─────────────────────────────────────────────────────────────

export async function exportTournamentJSON(tournament: Tournament): Promise<void> {
  const json = JSON.stringify(tournament, null, 2);
  const fileName = `${sanitiseFilename(tournament.name)}_${shortDate(tournament.createdAt)}.json`;
  const uri = FileSystem.cacheDirectory + fileName;

  await FileSystem.writeAsStringAsync(uri, json, {
    encoding: FileSystem.EncodingType.UTF8,
  });

  await share(uri);
}

// ─── Plain-text summary export ───────────────────────────────────────────────

export async function exportTournamentText(tournament: Tournament): Promise<void> {
  const text = buildTextSummary(tournament);
  const fileName = `${sanitiseFilename(tournament.name)}_${shortDate(tournament.createdAt)}.txt`;
  const uri = FileSystem.cacheDirectory + fileName;

  await FileSystem.writeAsStringAsync(uri, text, {
    encoding: FileSystem.EncodingType.UTF8,
  });

  await share(uri);
}

// ─── Text builder ─────────────────────────────────────────────────────────────

function buildTextSummary(tournament: Tournament): string {
  const lines: string[] = [];
  const participantMap = new Map(tournament.participants.map((p) => [p.id, p]));

  lines.push(`🏆  ${tournament.name}`);
  lines.push(`Format: Double Elimination`);
  lines.push(`Date: ${new Date(tournament.createdAt).toLocaleDateString()}`);
  lines.push(`Status: ${tournament.status}`);
  lines.push('');

  // Final standings (if complete)
  const placed = tournament.participants
    .filter((p) => p.placement !== null)
    .sort((a, b) => (a.placement ?? 99) - (b.placement ?? 99));

  if (placed.length > 0) {
    lines.push('── FINAL STANDINGS ──────────────────────');
    for (const p of placed) {
      const medal = p.placement === 1 ? '🥇' : p.placement === 2 ? '🥈' : p.placement === 3 ? '🥉' : `${p.placement}.`;
      lines.push(`${medal}  ${p.name}  (${p.wins}W – ${p.losses}L)`);
    }
    lines.push('');
  }

  // Match history
  const completed = tournament.matches.filter(
    (m) => m.status === 'complete' && !m.isBye,
  );

  if (completed.length > 0) {
    lines.push('── MATCH HISTORY ────────────────────────');
    for (const m of completed) {
      const p1 = participantMap.get(m.p1Id ?? '');
      const p2 = participantMap.get(m.p2Id ?? '');
      if (!p1 || !p2) continue;

      const section =
        m.bracket === 'winners'
          ? `WB R${m.round}`
          : m.bracket === 'losers'
          ? `LB R${m.round}`
          : m.round === 2
          ? 'GF Reset'
          : 'Grand Final';

      const w = participantMap.get(m.winnerId ?? '');
      lines.push(
        `[${section}]  ${p1.name} ${m.p1Score} – ${m.p2Score} ${p2.name}  → ${w?.name ?? '?'} wins`,
      );
    }
    lines.push('');
  }

  lines.push('Generated by BracketUp');
  return lines.join('\n');
}

// ─── Share helper ─────────────────────────────────────────────────────────────

async function share(uri: string): Promise<void> {
  const available = await Sharing.isAvailableAsync();
  if (!available) {
    throw new Error('Sharing is not available on this device');
  }
  await Sharing.shareAsync(uri);
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function sanitiseFilename(name: string): string {
  return name.replace(/[^a-z0-9_\-]/gi, '_').toLowerCase();
}

function shortDate(iso: string): string {
  return iso.slice(0, 10).replace(/-/g, '');
}
